name: "PHPUnit"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: "PHPUnit"
    env:
      LC_ALL: en_US.UTF-8
      CODE_COVERAGE: n
    continue-on-error: ${{ matrix.php-version == '7.2' }}

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "locked"
        operating-system:
          - "ubuntu-latest"
        composer:
          - "composer:v2"

#        include:
#          - php-version: 7.2
#            dependencies: "locked"
#          - php-version: 7.3
#            dependencies: "locked"
#          - php-version: 7.4
#            dependencies: "locked"
#          - php-version: 8.0
#            dependencies: "highest"
#          - php-version: 8.1
#            dependencies: "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring, xml, ctype, iconv
          tools: ${{matrix.composer}}

      - name: "Install dependencies"
        run: |
          composer update --no-interaction --no-progress

      - name: "Unit Tests"
        run: composer test-unit

      - name: "Integration Tests"
        run: composer test-int
